# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2022-11-12 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table_D_BP',
            fields=[
                ('dbp_id', models.IntegerField(primary_key=True, serialize=False)),
                ('datetime', models.CharField(max_length=30)),
                ('d_blood_pressure', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Table_OXY_S',
            fields=[
                ('oxy_s_id', models.IntegerField(primary_key=True, serialize=False)),
                ('datetime', models.CharField(max_length=30)),
                ('oxygen_saturation', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Table_PR',
            fields=[
                ('pr_id', models.IntegerField(primary_key=True, serialize=False)),
                ('datetime', models.CharField(max_length=30)),
                ('pulse_rate', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Table_S_BP',
            fields=[
                ('sbp_id', models.IntegerField(primary_key=True, serialize=False)),
                ('datetime', models.CharField(max_length=30)),
                ('s_blood_pressure', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Table_TEMP',
            fields=[
                ('temp_id', models.IntegerField(primary_key=True, serialize=False)),
                ('datetime', models.CharField(max_length=30)),
                ('temperature', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('u_id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=20)),
                ('email_id', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
