# Generated by Django 4.1.3 on 2022-11-23 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SHCS_app", "0005_rename_temp_details_tempe"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ambulance",
            fields=[
                ("u_id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("age", models.CharField(max_length=30)),
                ("gender", models.CharField(max_length=30)),
                ("location", models.CharField(max_length=20)),
                ("status", models.CharField(max_length=20)),
            ],
        ),
    ]
