# Generated by Django 3.2.16 on 2022-11-26 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SHCS_app', '0007_auto_20221126_1420'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
