# Generated by Django 3.2.16 on 2022-11-26 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SHCS_app', '0009_auto_20221126_1425'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ambulances',
            new_name='Ambulance',
        ),
    ]
