# Generated by Django 3.2.16 on 2022-12-01 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SHCS_app', '0010_rename_ambulances_ambulance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('u_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('humidity', models.CharField(max_length=30)),
                ('tempe', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Details',
        ),
    ]
