# Generated by Django 3.2.16 on 2022-12-01 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SHCS_app', '0011_auto_20221201_1001'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Detail',
            new_name='Details',
        ),
    ]
