# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2022-12-03 04:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SHCS_app', '0014_auto_20221203_1007'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Request',
            new_name='Requests',
        ),
    ]
