# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2022-12-08 05:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SHCS_app', '0015_auto_20221203_1008'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('r_id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=255)),
                ('p_address', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
