# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2022-12-08 05:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SHCS_app', '0016_auto_20221208_1037'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
    ]
