# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2022-12-15 11:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SHCS_app', '0019_auto_20221215_1708'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sellings',
            new_name='Selling',
        ),
    ]
