# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2022-12-17 07:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SHCS_app', '0022_selling_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selling',
            name='amount',
        ),
    ]
