# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2022-12-17 13:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SHCS_app', '0026_auto_20221217_1645'),
    ]

    operations = [
        migrations.RenameField(
            model_name='selling',
            old_name='r_id',
            new_name='r_id1',
        ),
    ]
