# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2022-12-19 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SHCS_app', '0027_auto_20221217_1844'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('r_id1', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('Ptype', models.CharField(max_length=255)),
                ('Prop_id', models.CharField(max_length=255)),
                ('details', models.CharField(max_length=255)),
                ('tkname', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('amount', models.CharField(max_length=255)),
            ],
        ),
    ]
