# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2022-12-20 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SHCS_app', '0030_auto_20221220_1307'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('r_id1', models.IntegerField(primary_key=True, serialize=False)),
                ('SName', models.CharField(max_length=255)),
                ('Saddr', models.CharField(max_length=255)),
                ('RName', models.CharField(max_length=255)),
                ('Raddr', models.CharField(max_length=255)),
                ('P_id', models.CharField(max_length=255)),
                ('Amount', models.CharField(max_length=255)),
                ('T_hash', models.CharField(max_length=255)),
            ],
        ),
    ]
