# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2022-12-22 03:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SHCS_app', '0033_auto_20221221_1245'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requesttk',
            fields=[
                ('r_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('tkname', models.CharField(max_length=255)),
                ('pid', models.CharField(max_length=255)),
                ('amount', models.CharField(max_length=255)),
                ('p_address', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=255)),
                ('pvt', models.CharField(max_length=255)),
                ('ptype', models.CharField(max_length=255)),
                ('details', models.CharField(max_length=255)),
                ('token', models.CharField(max_length=255)),
            ],
        ),
    ]
