# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2022-12-22 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SHCS_app', '0035_requesttk_cuname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyed',
            fields=[
                ('r_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('pname', models.CharField(max_length=255)),
                ('token', models.CharField(max_length=255)),
            ],
        ),
    ]
