# Generated by Django 4.1.5 on 2023-02-24 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("SHCS_app", "0039_auto_20230216_1448"),
    ]

    operations = [
        migrations.RemoveField(model_name="selling", name="status",),
    ]
