# Generated by Django 4.1.5 on 2023-02-24 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SHCS_app", "0040_remove_selling_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="selling",
            name="status",
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
