# Generated by Django 4.1.5 on 2023-02-24 14:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("SHCS_app", "0042_buyed_transaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="buyed",
            name="im",
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="buyed",
            name="p_type",
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
