# Generated by Django 4.1.5 on 2023-02-25 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SHCS_app", "0045_token"),
    ]

    operations = [
        migrations.CreateModel(
            name="Token1",
            fields=[
                ("r_id1", models.IntegerField(primary_key=True, serialize=False)),
                ("Name", models.CharField(max_length=255)),
                ("Ptype", models.CharField(max_length=255)),
                ("Prop_id", models.CharField(max_length=255)),
                ("details", models.CharField(max_length=255)),
                ("tkname", models.CharField(max_length=255)),
                ("image", models.CharField(max_length=255)),
                ("mobile", models.CharField(max_length=255)),
                ("status", models.CharField(max_length=255)),
                ("amount", models.CharField(max_length=255)),
                ("Preowner", models.CharField(max_length=255)),
                ("username", models.CharField(max_length=255)),
                ("token_count", models.CharField(max_length=255)),
                ("Cuholder", models.CharField(max_length=255)),
                ("hashh", models.CharField(max_length=255)),
                ("Button", models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(name="Token",),
    ]
