# Generated by Django 4.1.5 on 2023-02-25 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("SHCS_app", "0046_token1_delete_token"),
    ]

    operations = [
        migrations.RenameModel(old_name="Token1", new_name="Token",),
    ]
