# Generated by Django 4.1.5 on 2023-02-25 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("SHCS_app", "0047_rename_token1_token"),
    ]

    operations = [
        migrations.RemoveField(model_name="token", name="Preowner",),
    ]
