# Generated by Django 4.1.5 on 2023-02-25 12:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("SHCS_app", "0048_remove_token_preowner"),
    ]

    operations = [
        migrations.AddField(
            model_name="token",
            name="Preowner",
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
