# Generated by Django 4.1.5 on 2023-02-25 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("SHCS_app", "0049_token_preowner"),
    ]

    operations = [
        migrations.RemoveField(model_name="token", name="Preowner",),
    ]
