# Generated by Django 4.1.5 on 2023-02-25 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SHCS_app", "0051_buyed_tk"),
    ]

    operations = [
        migrations.AddField(
            model_name="buyed_tk",
            name="tok_co",
            field=models.CharField(default=10, max_length=255),
            preserve_default=False,
        ),
    ]
