# Generated by Django 4.1.5 on 2023-03-02 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SHCS_app", "0052_buyed_tk_tok_co"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sellingg",
            fields=[
                ("idd_s", models.IntegerField(primary_key=True, serialize=False)),
                ("r_id1", models.CharField(max_length=255)),
                ("Name", models.CharField(max_length=255)),
                ("Ptype", models.CharField(max_length=255)),
                ("Prop_id", models.CharField(max_length=255)),
                ("details", models.CharField(max_length=255)),
                ("image", models.CharField(max_length=255)),
                ("mobile", models.CharField(max_length=255)),
                ("amount", models.CharField(max_length=255)),
                ("username", models.CharField(max_length=255)),
                ("status", models.CharField(max_length=255)),
                ("hash1", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Tokenn",
            fields=[
                ("idd_t", models.IntegerField(primary_key=True, serialize=False)),
                ("r_id1", models.CharField(max_length=255)),
                ("Name", models.CharField(max_length=255)),
                ("Ptype", models.CharField(max_length=255)),
                ("Prop_id", models.CharField(max_length=255)),
                ("details", models.CharField(max_length=255)),
                ("tkname", models.CharField(max_length=255)),
                ("image", models.CharField(max_length=255)),
                ("mobile", models.CharField(max_length=255)),
                ("status", models.CharField(max_length=255)),
                ("amount", models.CharField(max_length=255)),
                ("username", models.CharField(max_length=255)),
                ("token_count", models.CharField(max_length=255)),
                ("Cuholder", models.CharField(max_length=255)),
                ("hashh", models.CharField(max_length=255)),
                ("Button", models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(name="Selling",),
        migrations.DeleteModel(name="Token",),
    ]
